CREATE TABLE IF NOT EXISTS freelancer_profiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  partner_id VARCHAR(20) NULL,
  full_name VARCHAR(150) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  location VARCHAR(150) NULL,
  profile_photo_path VARCHAR(500) NULL,
  date_of_birth DATE NULL,
  current_occupation VARCHAR(150) NULL,
  total_experience_years DECIMAL(4,1) NULL,
  digital_marketing_experience TEXT NULL,
  sales_experience TEXT NULL,
  skills TEXT NULL,
  specializations TEXT NULL,
  preferred_working_areas TEXT NULL,
  previous_agency_experience TEXT NULL,
  status ENUM('PENDING','VERIFIED','REJECTED','QUALIFIED','CERTIFIED','ACTIVE','SUSPENDED','INACTIVE') NOT NULL DEFAULT 'PENDING',
  rejection_reason TEXT NULL,
  verified_by INT NULL,
  verified_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_freelancer_profiles_user_id (user_id),
  UNIQUE KEY uq_freelancer_profiles_partner_id (partner_id),
  INDEX idx_freelancer_profiles_status (status),
  CONSTRAINT fk_freelancer_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_freelancer_profiles_verified_by FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
