CREATE TABLE IF NOT EXISTS test_attempts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  test_id INT NOT NULL,
  freelancer_id INT NOT NULL,
  attempt_number INT NOT NULL,
  selected_questions JSON NOT NULL,
  status ENUM('NOT_STARTED','IN_PROGRESS','SUBMITTED','EXPIRED','EVALUATED') NOT NULL DEFAULT 'NOT_STARTED',
  started_at DATETIME NULL,
  expires_at DATETIME NULL,
  submitted_at DATETIME NULL,
  evaluated_at DATETIME NULL,
  score DECIMAL(6,2) NULL,
  percentage DECIMAL(5,2) NULL,
  result ENUM('PASS','FAIL') NULL,
  time_used_seconds INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_test_attempts_test_freelancer_attempt (test_id, freelancer_id, attempt_number),
  INDEX idx_test_attempts_freelancer (freelancer_id),
  INDEX idx_test_attempts_test (test_id),
  INDEX idx_test_attempts_status (status),
  CONSTRAINT fk_test_attempts_test FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE,
  CONSTRAINT fk_test_attempts_freelancer FOREIGN KEY (freelancer_id) REFERENCES freelancer_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
