CREATE TABLE IF NOT EXISTS certificates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  certificate_number VARCHAR(30) NOT NULL,
  freelancer_id INT NOT NULL,
  test_attempt_id INT NULL,
  test_id INT NULL,
  webinar_id INT NULL,
  title VARCHAR(255) NOT NULL,
  issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('ACTIVE','REVOKED') NOT NULL DEFAULT 'ACTIVE',
  revoked_at DATETIME NULL,
  revoked_by INT NULL,
  revoke_reason TEXT NULL,
  pdf_path VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_certificates_certificate_number (certificate_number),
  UNIQUE KEY uq_certificates_freelancer_test (freelancer_id, test_id),
  INDEX idx_certificates_freelancer (freelancer_id),
  INDEX idx_certificates_status (status),
  CONSTRAINT fk_certificates_freelancer FOREIGN KEY (freelancer_id) REFERENCES freelancer_profiles(id) ON DELETE CASCADE,
  CONSTRAINT fk_certificates_test_attempt FOREIGN KEY (test_attempt_id) REFERENCES test_attempts(id) ON DELETE SET NULL,
  CONSTRAINT fk_certificates_test FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE SET NULL,
  CONSTRAINT fk_certificates_webinar FOREIGN KEY (webinar_id) REFERENCES webinars(id) ON DELETE SET NULL,
  CONSTRAINT fk_certificates_revoked_by FOREIGN KEY (revoked_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
