CREATE TABLE IF NOT EXISTS lead_activities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lead_id INT NOT NULL,
  actor_id INT NULL,
  activity_type ENUM(
    'LEAD_CREATED','ASSIGNED','REASSIGNED','UNASSIGNED',
    'PHONE_CALL','WHATSAPP','EMAIL','MEETING','VIDEO_CALL','SITE_VISIT',
    'NOTE_ADDED','FOLLOWUP_CREATED','FOLLOWUP_COMPLETED','FOLLOWUP_CANCELLED',
    'STATUS_CHANGED','CONVERTED','LOST'
  ) NOT NULL,
  description TEXT NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_lead_activities_lead_id (lead_id),
  CONSTRAINT fk_lead_activities_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_lead_activities_actor FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
