CREATE TABLE IF NOT EXISTS commissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lead_id INT NOT NULL,
  freelancer_id INT NOT NULL,
  commission_rule_id INT NULL,
  rule_service_name VARCHAR(150) NULL,
  rule_rate_type ENUM('PERCENTAGE','FIXED') NULL,
  rule_rate_value DECIMAL(10,2) NULL,
  sale_value DECIMAL(12,2) NOT NULL,
  commission_amount DECIMAL(12,2) NOT NULL,
  status ENUM('POTENTIAL','EARNED','APPROVED','PAYABLE','PAID') NOT NULL DEFAULT 'POTENTIAL',
  approved_by INT NULL,
  approved_at DATETIME NULL,
  created_by INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_commissions_lead_id (lead_id),
  INDEX idx_commissions_freelancer_id (freelancer_id),
  INDEX idx_commissions_status (status),
  CONSTRAINT fk_commissions_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_commissions_freelancer FOREIGN KEY (freelancer_id) REFERENCES freelancer_profiles(id) ON DELETE CASCADE,
  CONSTRAINT fk_commissions_rule FOREIGN KEY (commission_rule_id) REFERENCES commission_rules(id) ON DELETE SET NULL,
  CONSTRAINT fk_commissions_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_commissions_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
